//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhasyanovRijakov418
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListEntry
    {
        public int QuantityProduct { get; set; }
        public int PriceProduct { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> Waybill_ID { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Waybill Waybill { get; set; }
    }
}
