//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhasyanovRijakov418
{
    using System;
    using System.Collections.Generic;
    
    public partial class Waybill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Waybill()
        {
            this.ListEntry = new HashSet<ListEntry>();
        }
    
        public int Waybill_ID { get; set; }
        public System.DateTime Date_Waybill { get; set; }
        public double Price_Waybill { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> StorageID { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Storages Storages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListEntry> ListEntry { get; set; }
    }
}
